### ISSUE TITLE
Error on unmounting with active alerts

### ISSUE THREAD

**Issue by DmitryTezh** [creativetimofficial/react-notification-alert#2]
Hello Team!
When the component is unmounted and there are some active alerts (not yet dismissed) I got an error below:
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in NotificationAlert (at Sidebar.jsx:72)
    in div (at Sidebar.jsx:71)
    in Sidebar (at DashboardLayout.jsx:44)
    in div (at DashboardLayout.jsx:43)
    in DashboardLayout (created by Connect(DashboardLayout))
    in Connect(DashboardLayout) (at Routes.js:90)
    in Route (at Routes.js:88)
    in ProtectedRoute (created by Connect(ProtectedRoute))
    in Connect(ProtectedRoute) (at index.js:31)
As I undrestand there are some timeout callbacks pending which should be cleared on component  unmounting. Could you pls fix this issue?

**Comment by einazare** [comment]
Hello @DmitryTezh ,

Thank you for your interest in using this product.
Unfortunately i do not have time to make changes on this project, when i'll have some free/spare time, i'll do some much needed changes on it, but until then, you're going to use it as is, or if you have a fix, you can open a pull request.

Best,
Manu
