### ISSUE TITLE
Remove icon

### ISSUE THREAD

**Issue by shezankazi** [creativetimofficial/react-notification-alert#3]
When setting `options = { icon: undefined}` or just leaving icon away, the X-icon is still rendered. How do I disable the item?

**Comment by einazare** [comment]
Hello @shezankazi ,

Thank you for your interest in using our product and sorry for this late response (i've been on a small vacation - next week i also be on vacation).
That prop is used to add an icon to the notification as part of the message (see image attached).
![screen shot 2018-06-28 at 2 08 22 pm](https://user-images.githubusercontent.com/26245512/42030920-08bccbaa-7add-11e8-8702-491defda9bb0.png)
As of moment there is no way you can hide the close icon (just through css if you want).

Best,
Manu
