### ISSUE TITLE
onClick() notification

### ISSUE THREAD

**Issue by jrmartinez96** [creativetimofficial/react-notification-alert#7]
Is there any way to run a function when the notification is clicked??

**Comment by einazare** [comment]
Hello there, @jrmartinez96 ,

At the moment this functionality is not implemented, but it sounds something that could be added.
You can add a function to be clicked on a button inside the Notification alert.
Example: 
```
import React, { Component } from 'react';
import NotificationAlert from 'react-notification-alert';

var options = {};
options = {
    place: 'tl',
    message: (
        <div>
            <div>
                Welcome to <b>Now UI Dashboard React</b> - a beautiful freebie for every web developer.
                <br />
                <button className="btn btn-info" onClick={() => alert("hey")}>Click me to see an alert</button>
            </div>
        </div>
    ),
    type: "danger",
    icon: "now-ui-icons ui-1_bell-53",
    autoDismiss: 7
}

class App extends Component {
    myFunc(){
        this.refs.notify.notificationAlert(options);
    }
  render() {
    return (
      <div>
          <NotificationAlert ref="notify" />
          <button onClick={() => this.myFunc()}>Hey</button>
      </div>
    );
  }
}

export default App;
```

Could you please provide some more details on what you would expect with this functionality?
Would you like the function to be called, when clicking the actual notification, or the notification close button?

Hope this helps.

Best,
Manu

**Comment by tinuh** [comment]
Hi, I am having a issue with this as well. Using the js Notification API to send push notifications, the react application is saying that i cannot execute a function.

    PushNotification(msg, des, type){
        let notifi = new Notification(msg, {body: des, icon: Icon, onclick: () => window.focus()});
        let func = this
        notifi.onclick = function(event) {
            window.focus();
            func.startCountdown(this);
        }
    }
