### ISSUE TITLE
zIndex to small

### ISSUE THREAD

**Issue by giulianf** [creativetimofficial/react-notification-alert#8]
Hi, 

I use Navbar (top) from reactstrap.
If my place notif is in TOP (tl, tc, tr) the z-index of the NavBar is above the notification.
So it's impossible to close it with the across button 
To resume: 
1. NavBar to : z-index -> 1050
2. Notification :  z-index -> 1031

Regarding reactstrap components , is it possible art least to increase the z-index 1031 to 1051?

Thanks

**Comment by einazare** [comment]
Hello there, @giulianf ,

Create a wrapper div around the NotificationAlert, containing a class, or an id, for example:
```
        <div className="rna-container">
          <NotificationAlert ref="notificationAlert" />
        </div>
```
Then, add inside your css or scss the following code:
```
.rna-container {
    z-index: 1051;
    position: fixed;
}
```

Best,
Manu
